doppler:
  url: "wss://doppler.10.244.0.34.xip.io:443"
  token: "bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI4NGM5ZThhNy1kZTcyLTRmNjEtODBiMy1lN2VlYmQxNWIzMDgiLCJzdWIiOiIwZWM3M2Y2NC0zNzY2LTQ4ODEtODhhNy1mOTllYTIzOTQ1ZTkiLCJzY29wZSI6WyJzY2ltLnJlYWQiLCJjbG91ZF9jb250cm9sbGVyLmFkbWluIiwic2NpbS53cml0ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJwYXNzd29yZC53cml0ZSIsIm9wZW5pZCIsImNsb3VkX2NvbnRyb2xsZXIucmVhZCIsImRvcHBsZXIuZmlyZWhvc2UiXSwiY2xpZW50X2lkIjoiY2YiLCJjaWQiOiJjZiIsImF6cCI6ImNmIiwiZ3JhbnRfdHlwZSI6InBhc3N3b3JkIiwidXNlcl9pZCI6IjBlYzczZjY0LTM3NjYtNDg4MS04OGE3LWY5OWVhMjM5NDVlOSIsInVzZXJfbmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbiIsImlhdCI6MTQyMzg1ODIzOCwiZXhwIjoxNDIzODU4ODM4LCJpc3MiOiJodHRwczovL3VhYS4xMC4yNDQuMC4zNC54aXAuaW8vb2F1dGgvdG9rZW4iLCJhdWQiOlsiY2YiLCJzY2ltIiwiY2xvdWRfY29udHJvbGxlciIsInBhc3N3b3JkIiwib3BlbmlkIiwiZG9wcGxlciJdfQ.HqRfu1442AfzNAOUYM-P4aNm8UIEVM3-SWs0K59BEx9X0WuP6jsOQ0bYosnWbP6LotQiH_7HmKNflOkdwqocyvGi1CY5qtqbYep-PYz0B7wXf3kd2UGMH3WXm_Gt_ATcXNLMpNwjd_Opum_8iQHq1zRGclhQiPqkjCsQFxR-U_Q"

logging:
  level:
    org:
      springframework: OFF
endpoint: app
app:
  guid: b57efa70-d410-442a-8c7a-d9879fd10fce
  type: stream

  
