doppler:
  url: "wss://doppler.10.244.0.34.xip.io:443"
  token: "bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJjNGRkZDQ4OS1iZTU4LTQwMWYtOWQ0Zi1jYTE5ZTIzMGY3ODAiLCJzdWIiOiIwNWFjZjQ5My1lMDJjLTQ5ZmQtYTIyYy00YTU5NWNmOWUzNjQiLCJzY29w    ZSI6WyJzY2ltLnJlYWQiLCJjbG91ZF9jb250cm9sbGVyLmFkbWluIiwic2NpbS53cml0ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJwYXNzd29yZC53cml0ZSIsIm9wZW5pZCIsImNsb3VkX2NvbnRyb2xsZXIucmVhZCIsIm    RvcHBsZXIuZmlyZWhvc2UiXSwiY2xpZW50X2lkIjoiY2YiLCJjaWQiOiJjZiIsImF6cCI6ImNmIiwiZ3JhbnRfdHlwZSI6InBhc3N3b3JkIiwidXNlcl9pZCI6IjA1YWNmNDkzLWUwMmMtNDlmZC1hMjJjLTRhNTk1Y2Y5ZTM2NCIs    InVzZXJfbmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbiIsImlhdCI6MTQyMzc2OTY2MCwiZXhwIjoxNDIzNzcwMjYwLCJpc3MiOiJodHRwczovL3VhYS4xMC4yNDQuMC4zNC54aXAuaW8vb2F1dGgvdG9rZW4iLCJhdWQiOlsiY2    YiLCJzY2ltIiwiY2xvdWRfY29udHJvbGxlciIsInBhc3N3b3JkIiwib3BlbmlkIiwiZG9wcGxlciJdfQ.uXBNEbcR5ySYTdyLrQDfBOZbnFc7YFoRKGrczT4t031-NYP7G8ogMu7j4jmxp6KC0iGrtoePbXRjQ5A3LHEBYMitabu2z    UJKK0aspfC3MYELzTsiHtDLr7xa9eAjuvZI_VyNp2bA9xrjOae-PpKb-m9acEretIKpjQ8l0bAdPYo"

logging:
  level:
    org:
      springframework: OFF
endpoint: firehose

  
